spring:
  datasource:
    url: jdbc:mysql://192.168.113.128:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: cn.kurtis.study.mp.pojo.po # 实体类包
  mapper-locations: classpath*:mapper/**/*.xml # mapper xml 文件地址
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: on # 是否开启下划线-驼峰命名映射
    local-cache-scope: statement # 关闭一级缓存
    cache-enabled: on # 是否开启二级缓存
  global-config:
    banner: off
    db-config:
      id-type: auto # 默认 id 为数据库自增
      update-strategy: not_null
